//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Gen {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Gen.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio en Desarrollo.
        /// </summary>
        internal static string Development_Title_tx_01 {
            get {
                return ResourceManager.GetString("Development_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuestra constante busqueda de la mejora continua nos impulsa a desarrollar nuevos espacios de interes para nuestros clientes. En breve podras descubrir esta nueva seccion..
        /// </summary>
        internal static string Development_Title_tx_02 {
            get {
                return ResourceManager.GetString("Development_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Development_tx_01 {
            get {
                return ResourceManager.GetString("Development_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Development_tx_02 {
            get {
                return ResourceManager.GetString("Development_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiamos sus necesidades, perseguimos sus objetivos reduciendo los costes y gestionando el riesgo.
        /// </summary>
        internal static string Sub_Title_App {
            get {
                return ResourceManager.GetString("Sub_Title_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Innpovadag - Servicios Gestionados.
        /// </summary>
        internal static string Title_App {
            get {
                return ResourceManager.GetString("Title_App", resourceCulture);
            }
        }
    }
}
