//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Graphics {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Graphics.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico de barras con inclusion comparativa en y de diferentes productos segun su cantidad, eje x con coordenadas de tiempo, escalable en eje-x y con valores negativos para eje-y.
        /// </summary>
        internal static string Graph_bars_TypeA_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_bars_TypeA_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico de Barras donde cada etiqueta en x perteneciente a un item tiene su valor en y a nivel de cantidad. Grafica para comparativa entre varios Items.
        /// </summary>
        internal static string Graph_bars_TypeB_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_bars_TypeB_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Histograma A Cuantas veces en un parametro de tiempo se repite un valor concreto.
        /// </summary>
        internal static string Graph_bars_TypeC_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_bars_TypeC_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico de barras con random de valores.
        /// </summary>
        internal static string Graph_bars_TypeD_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_bars_TypeD_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico en linea con valor en y a lo largo del tiempo en eje x.
        /// </summary>
        internal static string Graph_lines_TypeA_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_lines_TypeA_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico de lineas multiple con comutacion.
        /// </summary>
        internal static string Graph_lines_TypeB_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_lines_TypeB_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico de linea con valores anidados, de una coleccion de datos con una misma variable de tiempo se suman todos los valores numericos para cada uno de esos tiempos..
        /// </summary>
        internal static string Graph_lines_TypeC_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_lines_TypeC_01_Txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafico estructura arbol.
        /// </summary>
        internal static string Graph_tree_TypeA_01_Txt_01 {
            get {
                return ResourceManager.GetString("Graph_tree_TypeA_01_Txt_01", resourceCulture);
            }
        }
    }
}
