//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Mnu {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mnu.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string _Mnu_Nav_Index_Index {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Index_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Innovadag.
        /// </summary>
        internal static string _Mnu_Nav_Index_Innovadag {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Index_Innovadag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte Power BI.
        /// </summary>
        internal static string _Mnu_Nav_Index_Support {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Index_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalan.
        /// </summary>
        internal static string _Mnu_Nav_Language_Cat {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cat.
        /// </summary>
        internal static string _Mnu_Nav_Language_Cat_short {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_Cat_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string _Mnu_Nav_Language_En {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ing.
        /// </summary>
        internal static string _Mnu_Nav_Language_En_short {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_En_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Castellano.
        /// </summary>
        internal static string _Mnu_Nav_Language_Esp {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_Esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cas.
        /// </summary>
        internal static string _Mnu_Nav_Language_Esp_short {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Language_Esp_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias.
        /// </summary>
        internal static string _Mnu_Nav_News {
            get {
                return ResourceManager.GetString("_Mnu_Nav_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud.
        /// </summary>
        internal static string _Mnu_Nav_Serv_01 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azure.
        /// </summary>
        internal static string _Mnu_Nav_Serv_02 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office 365.
        /// </summary>
        internal static string _Mnu_Nav_Serv_03 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dynamics 365.
        /// </summary>
        internal static string _Mnu_Nav_Serv_04 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cac.
        /// </summary>
        internal static string _Mnu_Nav_Serv_05 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicaciones y Seguridad.
        /// </summary>
        internal static string _Mnu_Nav_Serv_06 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BackUp Plus.
        /// </summary>
        internal static string _Mnu_Nav_Serv_07 {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Serv_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio Test de Monitorizacion de Datos.
        /// </summary>
        internal static string _Mnu_Nav_Test {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string _Mnu_Searcher_Search {
            get {
                return ResourceManager.GetString("_Mnu_Searcher_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Contenidos.
        /// </summary>
        internal static string _Mnu_Searcher_Search_Cont {
            get {
                return ResourceManager.GetString("_Mnu_Searcher_Search_Cont", resourceCulture);
            }
        }
    }
}
