//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Monitoring {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Monitoring.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Datos Amozon Web Services.
        /// </summary>
        internal static string Data_Amazon_Gen_title_01 {
            get {
                return ResourceManager.GetString("Data_Amazon_Gen_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Analitica Comparativa de Proveedores. Usos / Consumos.
        /// </summary>
        internal static string Data_AnlComp_Cons_title_01 {
            get {
                return ResourceManager.GetString("Data_AnlComp_Cons_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Analitica Comparativa de Proveedores. Gastos / Costes.
        /// </summary>
        internal static string Data_AnlComp_Exp_title_01 {
            get {
                return ResourceManager.GetString("Data_AnlComp_Exp_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Graficos Analitica de Gestion Empresarial.
        /// </summary>
        internal static string Data_AnlManag_title_01 {
            get {
                return ResourceManager.GetString("Data_AnlManag_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Analisis en funcion de los grupos de recursos.
        /// </summary>
        internal static string Data_Azure_Reso_title_01 {
            get {
                return ResourceManager.GetString("Data_Azure_Reso_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Analisis en funcion de las suscripciones.
        /// </summary>
        internal static string Data_Azure_Subc_title_01 {
            get {
                return ResourceManager.GetString("Data_Azure_Subc_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Datos Google Cloud.
        /// </summary>
        internal static string Data_Google_Gen_title_01 {
            get {
                return ResourceManager.GetString("Data_Google_Gen_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Datos G-Suite.
        /// </summary>
        internal static string Data_GSuite_Gen_title_01 {
            get {
                return ResourceManager.GetString("Data_GSuite_Gen_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Datos Office 365, Analisis por aplicaciones.
        /// </summary>
        internal static string Data_Office_Apl_title_01 {
            get {
                return ResourceManager.GetString("Data_Office_Apl_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Datos Office 365, Analisis por licencias.
        /// </summary>
        internal static string Data_Office_Lic_title_01 {
            get {
                return ResourceManager.GetString("Data_Office_Lic_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de visualizacion de datos generales del cliente.
        /// </summary>
        internal static string Data_Pos_Gen_title_01 {
            get {
                return ResourceManager.GetString("Data_Pos_Gen_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amazon Web Services.
        /// </summary>
        internal static string _Mnu_Nav_Amazon_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Amazon_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analiticas Comparativas.
        /// </summary>
        internal static string _Mnu_Nav_AnlComp_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_AnlComp_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparativa de Consumo / Usos.
        /// </summary>
        internal static string _Mnu_Nav_AnlComp_Cons_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_AnlComp_Cons_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparativas de Gastos / Costes.
        /// </summary>
        internal static string _Mnu_Nav_AnlComp_Exp_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_AnlComp_Exp_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analitica de Gestion Empresarial.
        /// </summary>
        internal static string _Mnu_Nav_AnlManag_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_AnlManag_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azure Cloud .
        /// </summary>
        internal static string _Mnu_Nav_Azure_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Azure_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de Recursos.
        /// </summary>
        internal static string _Mnu_Nav_Azure_Reso_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Azure_Reso_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscripciones.
        /// </summary>
        internal static string _Mnu_Nav_Azure_Subc_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Azure_Subc_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Google Cloud.
        /// </summary>
        internal static string _Mnu_Nav_Google_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Google_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a G-Suite.
        /// </summary>
        internal static string _Mnu_Nav_GSuite_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_GSuite_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office 365.
        /// </summary>
        internal static string _Mnu_Nav_Office_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Office_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicaciones.
        /// </summary>
        internal static string _Mnu_Nav_Office_Apl_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Office_Apl_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencias.
        /// </summary>
        internal static string _Mnu_Nav_Office_Lic_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Office_Lic_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posicion General.
        /// </summary>
        internal static string _Mnu_Nav_Pos_Gen_a {
            get {
                return ResourceManager.GetString("_Mnu_Nav_Pos_Gen_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Amazon Web Services A.
        /// </summary>
        internal static string _Tab_Amazon_a {
            get {
                return ResourceManager.GetString("_Tab_Amazon_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Amazon Web Services B.
        /// </summary>
        internal static string _Tab_Amazon_b {
            get {
                return ResourceManager.GetString("_Tab_Amazon_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Amazon Web Services C.
        /// </summary>
        internal static string _Tab_Amazon_c {
            get {
                return ResourceManager.GetString("_Tab_Amazon_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Amazon Web Services D.
        /// </summary>
        internal static string _Tab_Amazon_d {
            get {
                return ResourceManager.GetString("_Tab_Amazon_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa A. Usos / Consumos.
        /// </summary>
        internal static string _Tab_AnlComp_Cons_a {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Cons_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa B. Usos / Consumos.
        /// </summary>
        internal static string _Tab_AnlComp_Cons_b {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Cons_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa C. Usos / Consumos.
        /// </summary>
        internal static string _Tab_AnlComp_Cons_c {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Cons_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa Gastos / Costes A.
        /// </summary>
        internal static string _Tab_AnlComp_Exp_a {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Exp_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa Gastos / Costes B.
        /// </summary>
        internal static string _Tab_AnlComp_Exp_b {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Exp_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Comparativa Gastos / Costes C.
        /// </summary>
        internal static string _Tab_AnlComp_Exp_c {
            get {
                return ResourceManager.GetString("_Tab_AnlComp_Exp_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Gestion Empresarial A.
        /// </summary>
        internal static string _Tab_AnlManag_a {
            get {
                return ResourceManager.GetString("_Tab_AnlManag_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Gestion Empresarial B.
        /// </summary>
        internal static string _Tab_AnlManag_b {
            get {
                return ResourceManager.GetString("_Tab_AnlManag_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Analitica Gestion Empresarial C.
        /// </summary>
        internal static string _Tab_AnlManag_c {
            get {
                return ResourceManager.GetString("_Tab_AnlManag_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Recursos de Azure A.
        /// </summary>
        internal static string _Tab_Azure_Reso_a {
            get {
                return ResourceManager.GetString("_Tab_Azure_Reso_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Recursos de Azure B.
        /// </summary>
        internal static string _Tab_Azure_Reso_b {
            get {
                return ResourceManager.GetString("_Tab_Azure_Reso_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Recursos de Azure C.
        /// </summary>
        internal static string _Tab_Azure_Reso_c {
            get {
                return ResourceManager.GetString("_Tab_Azure_Reso_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Suscripciones de Azure A.
        /// </summary>
        internal static string _Tab_Azure_Subc_a {
            get {
                return ResourceManager.GetString("_Tab_Azure_Subc_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Suscripciones de Azure B.
        /// </summary>
        internal static string _Tab_Azure_Subc_b {
            get {
                return ResourceManager.GetString("_Tab_Azure_Subc_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Suscripciones de Azure C.
        /// </summary>
        internal static string _Tab_Azure_Subc_c {
            get {
                return ResourceManager.GetString("_Tab_Azure_Subc_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Google Cloud A.
        /// </summary>
        internal static string _Tab_Google_a {
            get {
                return ResourceManager.GetString("_Tab_Google_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Google Cloud B.
        /// </summary>
        internal static string _Tab_Google_b {
            get {
                return ResourceManager.GetString("_Tab_Google_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Google Cloud C.
        /// </summary>
        internal static string _Tab_Google_c {
            get {
                return ResourceManager.GetString("_Tab_Google_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Google Cloud D.
        /// </summary>
        internal static string _Tab_Google_d {
            get {
                return ResourceManager.GetString("_Tab_Google_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos G-Suite A.
        /// </summary>
        internal static string _Tab_GSuite_a {
            get {
                return ResourceManager.GetString("_Tab_GSuite_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos G-Suite B.
        /// </summary>
        internal static string _Tab_GSuite_b {
            get {
                return ResourceManager.GetString("_Tab_GSuite_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos G-Suite C.
        /// </summary>
        internal static string _Tab_GSuite_c {
            get {
                return ResourceManager.GetString("_Tab_GSuite_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos G-Suite D.
        /// </summary>
        internal static string _Tab_GSuite_d {
            get {
                return ResourceManager.GetString("_Tab_GSuite_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Aplicaciones Office 365 A.
        /// </summary>
        internal static string _Tab_Office_Apl_a {
            get {
                return ResourceManager.GetString("_Tab_Office_Apl_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Aplicaciones Office 365 B.
        /// </summary>
        internal static string _Tab_Office_Apl_b {
            get {
                return ResourceManager.GetString("_Tab_Office_Apl_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Aplicaciones Office 365 C.
        /// </summary>
        internal static string _Tab_Office_Apl_c {
            get {
                return ResourceManager.GetString("_Tab_Office_Apl_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Licencias Office 365 A.
        /// </summary>
        internal static string _Tab_Office_Lic_a {
            get {
                return ResourceManager.GetString("_Tab_Office_Lic_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Licencias Office 365 B.
        /// </summary>
        internal static string _Tab_Office_Lic_b {
            get {
                return ResourceManager.GetString("_Tab_Office_Lic_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graficos Licencias Office 365 C.
        /// </summary>
        internal static string _Tab_Office_Lic_c {
            get {
                return ResourceManager.GetString("_Tab_Office_Lic_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de visualizacion de datos generales del cliente.
        /// </summary>
        internal static string _Tab_Pos_Gen_a {
            get {
                return ResourceManager.GetString("_Tab_Pos_Gen_a", resourceCulture);
            }
        }
    }
}
