//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Monitoring_Acces {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Monitoring_Acces.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de Monitorización y Análisis.
        /// </summary>
        internal static string Title_Monit_tx_01 {
            get {
                return ResourceManager.GetString("Title_Monit_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos son la esencia. Todo lo que ve al explorar datos, crear gráficos y paneles o plantear preguntas con respuestas, se basa en un conjunto de datos. .
        /// </summary>
        internal static string Title_Monit_tx_02 {
            get {
                return ResourceManager.GetString("Title_Monit_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Title_Monit_tx_03 {
            get {
                return ResourceManager.GetString("Title_Monit_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area de alertas / Avisos / Notificaciones.
        /// </summary>
        internal static string _Alert_A_title_01 {
            get {
                return ResourceManager.GetString("_Alert_A_title_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string _Alert_A_title_02 {
            get {
                return ResourceManager.GetString("_Alert_A_title_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceder.
        /// </summary>
        internal static string _Btn_Acces_tx_01 {
            get {
                return ResourceManager.GetString("_Btn_Acces_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accede a tu escritorio personalizadoI con tu usuario de Active Directory.
        /// </summary>
        internal static string _Btn_Acces_tx_02 {
            get {
                return ResourceManager.GetString("_Btn_Acces_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analiza tu negocio con visualizaciones graficas e intuitivas. Supervisa el estado de tu empresa mediante los paneles activos..
        /// </summary>
        internal static string _Btn_Acces_tx_03 {
            get {
                return ResourceManager.GetString("_Btn_Acces_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string _Btn_Logout_tx_01 {
            get {
                return ResourceManager.GetString("_Btn_Logout_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string _Btn_Logout_tx_02 {
            get {
                return ResourceManager.GetString("_Btn_Logout_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualice los datos exclusivos de su cuenta personal. Conozca la informacion de consumos y gastos de sus aplicaciones..
        /// </summary>
        internal static string _Btn_Logout_tx_03 {
            get {
                return ResourceManager.GetString("_Btn_Logout_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio Emov.
        /// </summary>
        internal static string _Client_A_Title_tx_01 {
            get {
                return ResourceManager.GetString("_Client_A_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio Gac Group.
        /// </summary>
        internal static string _Client_B_Title_tx_01 {
            get {
                return ResourceManager.GetString("_Client_B_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio Tragsa.
        /// </summary>
        internal static string _Client_C_Title_tx_01 {
            get {
                return ResourceManager.GetString("_Client_C_Title_tx_01", resourceCulture);
            }
        }
    }
}
