//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Serv_Cloud {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Serv_Cloud.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo podemos ayudarle?.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_01 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión de nuestros Servicios Gestionados Cloud.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_02 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cual es el alcance de nuestros servicios?.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_03 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marco del servicio Gestionado.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_04 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte Servicios Gestionados.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_05 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuera de Alcance.
        /// </summary>
        internal static string Serv_Cloud_Title_txSub_06 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_txSub_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Gestionados Cloud.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Gestionados Cloud.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión y administración. Operación. Soporte. Gestión del cambio..
        /// </summary>
        internal static string Serv_Cloud_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes vs Cloud.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03 {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cloud
        ///Iaas  PaaS
        ///SaaS.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_a {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo creo máquinas?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_b {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuál me conviene más?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_c {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qué tipos hay?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_d {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Me sale a Cuenta?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_e {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estoy preparado?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_f {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qué es el Cloud?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_g {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo gestiono las identidades?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_h {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo puedo ir?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_i {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Están a salvo mis datos?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_j {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pueden convivir mis sistemas con el Cloud?.
        /// </summary>
        internal static string Serv_Cloud_Title_tx_03_k {
            get {
                return ResourceManager.GetString("Serv_Cloud_Title_tx_03_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEXTO ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Cloud_txt_01 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEXTO ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Cloud_txt_02 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEXTO ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Cloud_txt_03 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ·Aportando nuestra experiencia en estos entornos. La mayoría de las empresas que inician el cambio al Cloud no tiene técnicos formados.
        ///·Dando soporte a las incidencias que puedan producirse.
        ///·Asesorándole en la reducción de costes en la nube.
        ///·Liberando a su plantilla de la gestión adminstrativa y operativa.
        ///·Gestionando las consultas e incidencias, incluido el escalado al fabricante..
        /// </summary>
        internal static string Serv_Cloud_txt_04 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ·Asesoramiento: Nos queremos asegurar de que su experiencia en el cloud sea óptima. Para ello nos centraremos en las tareas relacionadas con el correcto aprovechamiento de las posibilidades que ofrece la nube en respuesta a las necesidades de su organización.
        ///·Apoyo en la gestión del cambio. Portal formativo en O365.
        ///·Nuestro equipo técnico realizará los cambios y gestionará las posibles incidencias desde el punto de vista técnico y administrativo siguiendo las directrices que nos marque descargando a su  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Serv_Cloud_txt_05 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio se basa en cuatro módulos que se aplican en función del ámbito contratado:
        ///·Gestión y administración, correspondiente a la parte de gestión administrativa propias de los portales según ámbito.
        ///·Operación, entendiéndose como la ejecución de los cambios que requiera el mantenimiento operativo del servicio dentro del ámbito contratado.
        ///·Soporte, en sus vertientes reactiva y de asesoramiento, con niveles de escalado 1 y 2 de InnovaDAG y 3 directamente del fabricante. 
        ///·Gestión del cambio (sólo p [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Serv_Cloud_txt_06 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio de Centro de atención a cliente, proporciona el punto de contacto inicial (para usuarios registrados seleccionados por el cliente) de la petición o incidencia en un formato 24*7 para incidencias y 12*8 para peticiones y cambios tanto en castellano como en inglés. Este servicio utiliza un software de registro de tickets basado en estándares (SAP).
        ///Este servicio incluye un contacto de Service Manager global del servicio que proporciona responsabilidad y gestión sobre el mismo.
        ///Hay otras modalida [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Serv_Cloud_txt_07 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El soporte se realizará ofreciendo:
        ///
        ///·Diagnóstico remoto.
        ///·Solución remota y restitución de la operativa, siempre y cuando nos autorice el Cliente y los procesos de actuación estén debidamente documentados.
        ///·Resolución de Consultas, atendiendo cuestiones técnicas y funcionales partiendo de las mejores prácticas y recomendaciones del fabricante.
        ///·Resolución de Incidencias según prioridad y protocolo de actuación.
        ///·Escalado a equipos de soporte on-site de nivel 2 o terceros.
        ///·Escalado a 3er nivel (fabr [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Serv_Cloud_txt_08 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ·No se considerarán dentro del alcance la transformación de servicios, ni la migración de datos (movimiento de un servicio hacia Office 365 o la implantación de soluciones híbridas). 
        ///·Administración o intervención sobre dispositivos o servicios On Premise como extremos de VPN o servicios de aplicaciones.
        ///·Instalación/remediación/homologación de cualquier aplicación tanto del Cliente como de terceros para adaptarla a la nueva plataforma/sistema.
        ///·Upgrade de versiones del Directorio Activo o cualquier otr [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Serv_Cloud_txt_09 {
            get {
                return ResourceManager.GetString("Serv_Cloud_txt_09", resourceCulture);
            }
        }
    }
}
