//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Services.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de informacion y novedades. Tus Newsletters.
        /// </summary>
        internal static string News_Title_tx_01 {
            get {
                return ResourceManager.GetString("News_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manten al dia tu informacion, suscribete a nuestra newsletter mensual y recibiras las noticias mas relevantes del sector..
        /// </summary>
        internal static string News_Title_tx_02 {
            get {
                return ResourceManager.GetString("News_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Gestionados Ambitos de Actuacion.
        /// </summary>
        internal static string Serv_Area_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Area_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambitos de Actuacion.
        /// </summary>
        internal static string Serv_Area_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Area_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscamos resolver sus necesidades, enfocamos nuestros esfuerzos en la optimizacion de sus activos..
        /// </summary>
        internal static string Serv_Area_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Area_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito Servicios Gestionados Azure.
        /// </summary>
        internal static string Serv_Azure_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Azure_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito SsGg Azure.
        /// </summary>
        internal static string Serv_Azure_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Azure_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IaaS y PaaS.
        /// </summary>
        internal static string Serv_Azure_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Azure_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TITULAR ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Azure_Title_tx_03 {
            get {
                return ResourceManager.GetString("Serv_Azure_Title_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ámbito de la prestación del servicio Gestionado Azure abarca los  servicios IaaS y PaaS  y responde a la operación de los diferentes servicios como plataforma entregados por Azure (https://azure.microsoft.com/es-es/services/)..
        /// </summary>
        internal static string Serv_Azure_txt_01 {
            get {
                return ResourceManager.GetString("Serv_Azure_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En general el servicio abarca todo lo que se pueda realizar con el acceso a la subscripción y portal de Azure pero no a los S.O. y aplicaciones que puedan residir en las máquinas..
        /// </summary>
        internal static string Serv_Azure_txt_02 {
            get {
                return ResourceManager.GetString("Serv_Azure_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Serv_Azure_txt_03 {
            get {
                return ResourceManager.GetString("Serv_Azure_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Backup Plus.
        /// </summary>
        internal static string Serv_Backuplus_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Backuplus_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios Backup Plus.
        /// </summary>
        internal static string Serv_Backuplus_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Backuplus_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus aplicaciones OnPremise con la seguridad de la nube.
        /// </summary>
        internal static string Serv_Backuplus_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Backuplus_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -Externalización - Protección off-site del dato on premise.
        ///-Backup Eficiente.
        ///-Agente de Backup para entornos Microsoft a través de software del fabricante CloudBerry.
        ///-Recuperación desde la nube.
        /// </summary>
        internal static string Serv_Backuplus_txt_01 {
            get {
                return ResourceManager.GetString("Serv_Backuplus_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Serv_Backuplus_txt_02 {
            get {
                return ResourceManager.GetString("Serv_Backuplus_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Serv_Backuplus_txt_03 {
            get {
                return ResourceManager.GetString("Serv_Backuplus_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de Atencion al Cliente.
        /// </summary>
        internal static string Serv_CAC_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_CAC_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de Atencion al Cliente.
        /// </summary>
        internal static string Serv_CAC_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_CAC_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte tecnico profesional.
        /// </summary>
        internal static string Serv_CAC_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_CAC_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Serv_CAC_txt_01 {
            get {
                return ResourceManager.GetString("Serv_CAC_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Serv_CAC_txt_02 {
            get {
                return ResourceManager.GetString("Serv_CAC_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios de comunicaciones y seguridad.
        /// </summary>
        internal static string Serv_Com_Sec_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Com_Sec_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicacion y Seguridad.
        /// </summary>
        internal static string Serv_Com_Sec_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Com_Sec_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TITULAR ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Com_Sec_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Com_Sec_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TEXTO ARGUMENTO DE VENTA.
        /// </summary>
        internal static string Serv_Com_Sec_txt_01 {
            get {
                return ResourceManager.GetString("Serv_Com_Sec_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito Servicios Gestionados Dynamics 365.
        /// </summary>
        internal static string Serv_Dynam_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_Dynam_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito SsGg Dynamics 365.
        /// </summary>
        internal static string Serv_Dynam_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_Dynam_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte en plataforma de aplicaciones comunes..
        /// </summary>
        internal static string Serv_Dynam_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_Dynam_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft Dynamics 365 le da libertad de elección ya que dispone de aplicaciones empresariales inteligentes de CRM y ERP. Empiece sólo con lo que necesite para dirigir su negocio e impresione a sus clientes. Añada aplicaciones a medida que cambien sus necesidades.
        ///Cada aplicación resuelve problemas reales y aporta valor real. Pero si las combina, obtendrá la potencia y las posibilidades adecuadas para transformar su negocio..
        /// </summary>
        internal static string Serv_Dynam_txt_01 {
            get {
                return ResourceManager.GetString("Serv_Dynam_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejore sus decisiones con datos. Al integrar Microsoft Power BI, Cortana Intelligence y Azure Machine Learning, Dynamics 365 le ayuda a usted y a sus empleados a convertir Big Data en planes viables..
        /// </summary>
        internal static string Serv_Dynam_txt_02 {
            get {
                return ResourceManager.GetString("Serv_Dynam_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito Servicios Gestionados O365.
        /// </summary>
        internal static string Serv_O365_Title_tx_01 {
            get {
                return ResourceManager.GetString("Serv_O365_Title_tx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ámbito SsGg Office 365.
        /// </summary>
        internal static string Serv_O365_Title_tx_01_lr {
            get {
                return ResourceManager.GetString("Serv_O365_Title_tx_01_lr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adecuaciones y cambios para optimizar las necesidades..
        /// </summary>
        internal static string Serv_O365_Title_tx_02 {
            get {
                return ResourceManager.GetString("Serv_O365_Title_tx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office donde y cuando lo necesites.
        /// </summary>
        internal static string Serv_O365_Title_tx_03 {
            get {
                return ResourceManager.GetString("Serv_O365_Title_tx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuando trabajes en la oficina o durante los desplazamientos, tienes un conjunto de herramientas de productividad conocida y de primera clase. Las aplicaciones de Office (siempre la versión más reciente) te permiten crear, editar y compartir con cualquier persona y en tiempo real, desde tu equipo PC o Mac, o desde cualquier Dispositivo iOS, Android™ o Windows.
        /// </summary>
        internal static string Serv_O365_txt_01 {
            get {
                return ResourceManager.GetString("Serv_O365_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personaliza las direcciones de correo electrónico de categoría empresarial con el nombre de tu empresa para conseguir el reconocimiento de la marca y promociona el negocio con materiales de marketing personalizados y fáciles de crear. Mejora las relaciones con los clientes y compañeros de trabajo con una amplia variedad de herramientas de comunicación, desde correo electrónico y mensajería instantánea a redes sociales videoconferencia..
        /// </summary>
        internal static string Serv_O365_txt_02 {
            get {
                return ResourceManager.GetString("Serv_O365_txt_02", resourceCulture);
            }
        }
    }
}
